name: Server Deployment Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]

permissions:
    contents: read
    checks: write

jobs:
    client_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install client dependencies
              run: cd client && npm install

            - name: Build App
              run: |
                  cd client
                  npm run build 
                  cp -r dist ../server

    server_deployment_pipeline:
        needs: [client_deployment_pipeline]
        runs-on: ubuntu-20.04
        steps:
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install server dependencies
              run: cd server && npm install

            - name: Connect to database
              run: |
                  cd server
                  flyctl proxy 5432 -a hygiea-emr-db-test &
                  sleep 10
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

            - name: Jest Test
              run: |
                  cd server
                  npm run test
              env:
                  PORT: ${{ secrets.PORT }}
                  TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  SECRET: ${{ secrets.SECRET }}

            - name: Publish Test Results
              uses: mikepenz/action-junit-report@v4
              if: success() || failure()
              with:
                  report_paths: "server/src/test/_result/results.xml"

            - name: Deploy App
              if: ${{ github.event_name == 'push' }}
              run: |
                  cd server
                  flyctl deploy --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    tag_release:
        needs: [server_deployment_pipeline]
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - name: Bump version and push tag
              uses: anothrNick/github-tag-action@1.64.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
