name: Server Deployment Pipeline

on:
    push:
        branches:
            - main

jobs:
    server_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
              with:
                  node-version: "20"

            - name: Install dependencies
              run: cd server && npm install

            - name: Connect to Postgres
              run: flyctl proxy 5432 -a hygiea-emr-db-test && flyctl postgres connect -a hygiea-emr-db-test
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
