name: Server Deployment Pipeline

on:
    push:
        branches:
            - main

jobs:
    server_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
              with:
                  node-version: "20"

            - name: Install dependencies
              run: cd server && npm install

            - name: Proxy and connect to test database
              run: |
                  cd server
                  flyctl proxy 5432 -a hygiea-emr-db-test &
                  sleep 10
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

            - name: Test
              run: cd server && npm run test
              env:
                  PORT: ${{ secrets.PORT }}
                  TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
